version: "1.0"

linter: jetbrains/qodana-jvm:latest

failThreshold: 0

coverage:
  freshThreshold: 60
  totalThreshold: 50

include:
  - name: JavaDoc
  - name: UnusedDeclaration
  - name: ConstantConditions
  - name: NullableProblems

exclude:
  - name: SpellCheckingInspection

excludes:
  - name: ".*"
    paths:
      - ".git"
      - "target"